version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev